### ISSUE TITLE
FreePBX Superfecta access to your server

### ISSUE THREAD

**Issue by jacotec** [kettenbach-it/asterisk-fastagi-tellows#1]
Hi Volker,

I'm really seraching for a Tellows integration for FreePBX (which uses Asterisk under the hood), but Macro support is not that optimal for FreePBX. But FreePBX offers an embedded perfect module for Spam detection and numbers lookup named Superfecta. This is a standard module included in FreePBX.

As I think FreePBX installations are much more widespread than "raw Asterisk" installations I'd really appreciate if your docker image could be updated to be queried by Superfecta.

I've opened a thread in the FreePBX forums and one member made a quick script for querying the Tellows website which returns the score for a given number. Basically this works, but it's far from "official" and I'm looking for a way to connect this to Tellows using the API with an official key.

That's where my idea kicks in - do you think you can extend your solution to be able to respond to a Superfecta query from FreePBX with the Spam score number from Tellows, so the Superfecta script kann contact your server instead of the Tellows website? Your project already handles the "official" contact to the Tellow servers.

The forum thread can be found here: https://community.freepbx.org/t/online-blacklist-reputation-check-using-tellows-api/94842/8

**Comment by kettenbach-it** [comment]
Hi Marko,

You don't need macros to use the tool. I only mentioned macros in the documentation because my example diaplan uses one.
The tool is simply a FastAGI server that you can call from anywhere in the dialplan - whether from a macro or not.
In principle, there are various options for integration in Superfecta - although I am not familiar with Superfecta:
- Superfecta calls my system via AGI Call (if it can do AGI)
- You call my system via AGI before Superfecta and pass the result in a variable to Superfecta (if it can read variables from asterisk)
- Superfecta calls my system via another interface, e.g. REST. However, this interface does not yet exist
- Superfecta calls Tellows directly - that would certainly make more sense than the last option, so I wouldn't build an interface for Superfecta

I hope that helps.

**Comment by jacotec** [comment]
Hi Volker,

thank you for your fast and detailed response. I'll ask if Superfecta can deal with AGI calls.

I just thought that your container maybe could respond to the standard call Superfecta can do

`https://www.tellows.de/basic/num/$thenumber?json=1`

in case it would be passed to your webserver. What it currently does not is to use the authentication (purchased API access) or any validation check of the response (which your project all does). So basically a kind of "proxy use", calling your webserver instead of the tellows one

 `https://ip.of.the.container/basic/num/$thenumber?json=1`

**Comment by kettenbach-it** [comment]
Technically yes, but I'm not sure if I want to provide such in interface "design-wise" - I mean: why don't you just implement those features in Superfecta. In the end it's a couple of lines of code.... And I don't have to maintain an interface for another project that I do not use

**Comment by jacotec** [comment]
I have enhanced the initial script for Superfecta and it seems to work pretty well. Thank you for your ideas and support!
